<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>$title$ - Syntactic.org</title>
    <link  href="http://fonts.googleapis.com/css?family=Inconsolata:regular" rel="stylesheet" type="text/css">
    <link  href="http://fonts.googleapis.com/css?family=Crimson+Text:regular" rel="stylesheet" type="text/css" >
    <link rel="stylesheet" type="text/css" href="/static/style.css" />
    <link href="/feed.xml" type="application/atom+xml" rel="alternate" title="ATOM Feed" />
  </head>
  <body>
    <div id="container">
      <div id="header">
        $header()$
        <div class="clear"></div>
      </div>
      <div id="content">
        $content()$
      </div>
      <div id="sidebar">
        $sidebar()$
      </div>
      <div class="clear"></div>
      <div id="footer">
        $footer()$
      </div>
    </div>
  </body>
</html>
