<ul id="nav">
<li>Blog</li>
<li>Projects</li>
<li>Resume</li>
<li id="goodreadsWidget">
  <!-- BEGIN GoodReads widget -->
  <!-- <script src="http://www.goodreads.com/review/grid_widget/1856350.Currently%20reading?cover_size=medium&amp;num_books=20&amp;order=d&amp;shelf=currently-reading&amp;sort=date_added&amp;widget_id=1264628778" type="text/javascript" charset="utf-8"> -->
  <!-- </script> -->
  <!-- END of GoodReads widget -->
</li>
<li id="deliciousWidget" style="clear: both">
  <!-- <script type="text/javascript" src="http://feeds.delicious.com/v2/js/ciscbrain?title=My+Bookmarks&icon=s&count=7&sort=date"></script> -->
</li>
</ul>
